export const GalleryData = [
  {
    id: 1,
    titile: "Category01",
    h5: "CXO TECHBOT OCTOBER 2023",
    h6: "CXO TechBot-Your digital Sherpa to Tech Engima...",
    link: "issuu.com",
    p: "Last updated 3 mins ago",
    image: "/assets/images/mag01.jpg",
  },
  {
    id: 2,
    titile: "Category01",
    h5: "CXO TECHBOT OCTOBER 2023",
    h6: "CXO TechBot-Your digital Sherpa to Tech Engima...",
    link: "issuu.com",
    p: "Last updated 3 mins ago",
    image: "/assets/images/mag02.jpeg",
  },
  {
    id: 3,
    titile: "Category02",
    h5: "CXO TECHBOT OCTOBER 2023",
    h6: "CXO TechBot-Your digital Sherpa to Tech Engima...",
    link: "issuu.com",
    p: "Last updated 3 mins ago",
    image: "/assets/images/mag03.jpeg",
  },
  {
    id: 4,
    titile: "Category02",
    h5: "CXO TECHBOT OCTOBER 2023",
    h6: "CXO TechBot-Your digital Sherpa to Tech Engima...",
    link: "issuu.com",
    p: "Last updated 3 mins ago",
    image: "/assets/images/mag04.jpg",
  },
  {
    id: 5,
    titile: "Category03",
    h5: "CXO TECHBOT OCTOBER 2023",
    h6: "CXO TechBot-Your digital Sherpa to Tech Engima...",
    link: "issuu.com",
    p: "Last updated 3 mins ago",
    image: "/assets/images/mag05.jpeg",
  },
  {
    id: 6,
    titile: "Category03",
    h5: "CXO TECHBOT OCTOBER 2023",
    h6: "CXO TechBot-Your digital Sherpa to Tech Engima...",
    link: "issuu.com",
    p: "Last updated 3 mins ago",
    image: "/assets/images/mag06.jpeg",
  },
];
